"""empty message

Revision ID: 49f5599eaa9a
Revises: 
Create Date: 2025-05-18 11:52:01.281837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f5599eaa9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=15), nullable=False),
    sa.Column('time', sa.String(length=15), nullable=False),
    sa.Column('level', sa.String(length=15), nullable=False),
    sa.Column('title', sa.String(length=15), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=20), nullable=True),
    sa.Column('file_name', sa.String(length=20), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('board')
    op.drop_table('user')
    op.drop_table('join_list')
    # ### end Alembic commands ###
